# Generated by Django 2.0.4 on 2018-04-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_User',
            fields=[
                ('email_address', models.EmailField(help_text='Email address used to register in application. Typically used to sent alerts, account updates and other news.', max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='User name for login to the application. Replaces need of using long email address.', max_length=15)),
            ],
        ),
    ]
