# Generated by Django 2.0.4 on 2018-04-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robin_UserReport', '0002_auto_20180425_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='The name of an associated bank.', max_length=15)),
                ('logo_id', models.CharField(help_text='Path to the icon to display that corresponds to the respective bank.', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePagePresentation',
        ),
    ]
